name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_platform_network:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  built_value_generator: ^6.4.0


flutter:

  uses-material-design: true